In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import joblib

In [5]:
dataset = pd.read_csv('workout_split_training.csv')
dataset = dataset.drop(columns=['case_id'])
df = dataset.copy()

reg_target = ['split_type']
Y = df[reg_target]

X = df.drop(columns=reg_target)





In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42, stratify=Y
)

model = XGBClassifier(
    objective="multi:softmax",
    num_class=3,
    n_estimators=200,
    max_depth=4,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    tree_method="hist",
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)


print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification report:")
print(classification_report(y_test, y_pred))



Confusion matrix:
[[290  29  36]
 [ 12 475  37]
 [ 19  27 675]]

Classification report:
              precision    recall  f1-score   support

           0       0.90      0.82      0.86       355
           1       0.89      0.91      0.90       524
           2       0.90      0.94      0.92       721

    accuracy                           0.90      1600
   macro avg       0.90      0.89      0.89      1600
weighted avg       0.90      0.90      0.90      1600



In [7]:
joblib.dump(model, 'workout_split_xgb_model.pkl')
print("Modell elmentve: mworkout_split_xgb_model.pkl")

Modell elmentve: mworkout_split_xgb_model.pkl
